<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VegePlusFish</name>
   <tag></tag>
   <elementGuidId>dbc96091-d418-47e4-aa41-0086b18c2284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div[3]/div[2]/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>diet-card__wrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WEGE plus RYBYDieta wegetariańska uwzględniająca ryby 2 razy w tygodniu... więcej</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;steps-page&quot;]/div[@class=&quot;steps-page__container&quot;]/div[@class=&quot;position-rel width-100-per&quot;]/div[@class=&quot;box-step&quot;]/div[@class=&quot;steps-page__list steps-page__list--variants steps-page__list--grid-order-form&quot;]/div[@class=&quot;diet-card diet-card--order-form diet-card--variant-card noselect&quot;]/div[@class=&quot;diet-card__container&quot;]/div[@class=&quot;diet-card__wrapper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div[3]/div[2]/div[2]/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WEGE plus RYBYDieta wegetariańska uwzględniająca ryby 2 razy w tygodniu... więcej' or . = 'WEGE plus RYBYDieta wegetariańska uwzględniająca ryby 2 razy w tygodniu... więcej')]</value>
   </webElementXpaths>
</WebElementEntity>
