<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EcoBox_Quantity</name>
   <tag></tag>
   <elementGuidId>676b5ed7-ff9f-45a4-8210-ce80f248ec11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.label-m.spacer-horizontal-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div[4]/div[2]/div[2]/div/div/div[3]/div/div[3]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-m spacer-horizontal-14</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;steps-page&quot;]/div[@class=&quot;steps-page__container&quot;]/div[@class=&quot;position-rel width-100-per&quot;]/div[@class=&quot;box-step box-step--overflow-hidden&quot;]/div[@class=&quot;position-rel&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-pointer-events steps-page__list steps-page__list--small-margin-top overflow-inherit&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide height-auto width-auto&quot;]/div[@class=&quot;extras-order extras-order--selected&quot;]/div[@class=&quot;display-flex flex-wrap justify-content-space-between align-items-center&quot;]/div[@class=&quot;display-flex spacer-top-8&quot;]/div[@class=&quot;extras-order__amount&quot;]/div[@class=&quot;amount-carousel&quot;]/span[@class=&quot;label-m spacer-horizontal-14&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div[4]/div[2]/div[2]/div/div/div[3]/div/div[3]/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dodaj'])[2]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuń'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koktajl wzmocnij odporność'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
   </webElementXpaths>
</WebElementEntity>
